### ISSUE TITLE
Analytic Plan (checklist)

### ISSUE THREAD

**Issue by philsf** [philsf-biostat/SAR-2021-004-TV#2]
- [x] Specify objective + hypotheses
- [x] Select variables
- [x] document data cleaning procedures
- [x] Specify analyses
- [x] render document
- [ ] remove watermark
- [x] update README link

**Comment by philsf** [comment]
Watermark kept until primary outcome is clarified. Title still remains to be defined.
