### ISSUE TITLE
checklist for final report (SAR-2021-004-TV)

### ISSUE THREAD

**Issue by philsf** [philsf-biostat/SAR-2021-004-TV#7]
- [x] New data received
- [x] Title
- [x] Objective
- [x] Data & Methods (from SAP)
- [x] Conclusions match the results
- [x] remove watermark
- [x] update TOC
- [x] render private + public version
- [x] update README status + links
